# Домашнее задание «Библиотека numpy. Вычислительные задачи»

## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
N = 10
np.arange(N-1, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
my_matrix = np.diag(np.arange(N-1, -1, -1))
my_matrix

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
my_matrix.sum() #Можем посчитать общую сумму, так как элементы матрицы, находящиеся вне главной диагонале, равны 0

45

## Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [5]:
left = np.array( 
    [
        [4, 2, 1],
        [1, 3, 0],
        [0, 5, 4]
    ] 
)

In [6]:
right = np.array([4, 12, -3])

In [7]:
from numpy import linalg
answer = linalg.solve(left, right)
print(answer)

[ 0.46666667  3.84444444 -5.55555556]


In [8]:
#Осуществим проверку преавильности решения
np.allclose(np.dot(left, answer), right)

True

## Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [9]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [10]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

### Решение:

Напишем функцию определения косинуса угла между векторами:

In [11]:
def cosine(a, b):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    length_a = np.linalg.norm(a) #Определим длину вектора a
    length_b = np.linalg.norm(b) #Определим длину вектора b
    
    return np.dot(a, b) / (length_a * length_b)

In [12]:
def similar_user(users_stats, next_user_stats):
    """
    Функция находит для нового пользователя самого похожего пользователя из базы пользователей.
    """
    max_result = 0
    number = 1
    for user in users_stats:
        new_result = cosine(user, next_user_stats)
        if max_result <= new_result:
            max_result = new_result
            max_number = number
        number +=1
    return (f'Самый похожий пользователь -  User {max_number}')   

In [13]:
similar_user(users_stats, next_user_stats)

'Самый похожий пользователь -  User 8'